version: "3"

services:
  django:
    build:
      context: .
      dockerfile: django_dockerfile
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    env_file:
      - ./.env
    user: "1000:1000"

  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - django
