# Generated by Django 4.0.5 on 2022-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='add_like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
