# Generated by Django 4.0.5 on 2022-06-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_posts_add_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='content',
        ),
    ]
