# Generated by Django 4.0.5 on 2022-06-17 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comments_name_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='myNote', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(default='default', max_length=155),
        ),
    ]
