# Generated by Django 4.0.5 on 2022-06-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notes_name_alter_notes_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
