# Generated by Django 4.0.5 on 2022-06-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comments_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
    ]
