# Generated by Django 4.0.5 on 2022-06-29 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_comments_name_alter_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(default='visitor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
